export const analysis = <i class="fa-solid fa-chart-pie"></i>
export const dashboard = <i class="fa-solid fa-chart-simple"></i>
export const payment = <i class="fa-solid fa-credit-card"></i>
export const budget = <i class="fa-solid fa-sack-dollar"></i>
export const transactions = <i className="fa-solid fa-credit-card"></i>
export const categories = <i className="fa-solid fa-tags"></i>
export const accounts = <i className="fa-solid fa-wallet"></i>
export const settings = <i className="fa-solid fa-cog"></i>
export const logout = <i className="fa-solid fa-sign-out"></i>
export const login = <i class="fa-solid fa-user"></i>
export const register = <i class="fa-solid fa-id-card"></i>
export const trend = <i className="fa-solid fa-money-bill-trend-up"></i>
export const expenses = <i className="fa-solid fa-money-bill-transfer"></i>
export const money = <i class="fa-solid fa-receipt"></i>
export const users = <i className="fa-solid fa-users-between-lines"></i>
export const dollar = <i className="fa-solid fa-dollar-sign"></i>
export const calender = <i className="fa-solid fa-calendar"></i>
export const comment = <i className="fa-solid fa-comment"></i>
export const plus = <i className="fa-solid fa-plus"></i>
export const trash = <i className="fa-solid fa-trash"></i>
export const signout = <i className="fa-solid fa-right-from-bracket"></i>
export const tick = <i className="fa-solid fa-check"></i>